import type {Metadata} from "next";
import "./globals.css";
import {cn} from "@/lib/utils";
import {pretendard} from "@/lib/fonts";
import React from "react";
import Navbar from "@/components/navbar";
import {ThemeProvider} from "@/components/theme/theme-provider";

export const metadata: Metadata = {
    title: "은현의 포트폴리오",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
        <body className={cn("antialiased", pretendard.className)}>
        <ThemeProvider>
            <div className="sticky top-0 z-50 bg-white">
                <Navbar/>
            </div>
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}